@startuml arch

component main
component api
component domain
component service
component repository
component infrastructure

main ..> api
main ..> infrastructure
api ..> domain
repository ..> domain
api ..> service
service ..> domain

@enduml
